### ISSUE TITLE
Organisation -> Organization

### ISSUE THREAD

**Issue by Aadit-Ambadkar** [arashnrim/website#22]
Organization is accepted in AmE, but organisation is not.

I would recommend changing to organization (although organisation is technically acceptable in BrE).

**Comment by arashnrim** [comment]
Hello Aadit, thanks for stopping by!

You make a valid point about the spelling of organis/zation in both variants, but my website was intentionally written in BrE since that's the variation of English I was brought up with. You may notice this in other places as well (like "behaviour"). It's purely a personal choice. For this reason, I won't accept your recommendation, but thank you anyway for taking a look at my website's repository!
